version: "3"
services:
  db:
    image: mysql:5.7
    container_name: cr-db
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/:ro
    networks:
      - cr-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8088:80
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${DATABASE_PORT}
    networks:
      - cr-network
  api:
    build:
      context: ./cr-api
      dockerfile: dockerfile
    container_name: cr-api
    restart: always
    environment:
      - DATABASE_HOST=db
      - PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    links:
      - db
    networks:
      - cr-network
  web:
    build:
      context: ./cr-fe
      dockerfile: dockerfile
    container_name: cr-web
    restart: always
    ports:
      - 8080:8080
    environment:
      - VUE_APP_API_ENDPOINT=http://api:${API_PORT}
    depends_on:
      - api
    links:
      - api
    networks:
      - cr-network

volumes:
  mysqldata:

networks:
  cr-network:
